### ISSUE TITLE
Milestone to a proper project!

### ISSUE THREAD

**Issue by aswinmurali-io** [crysalisdevs/bakecode#7]
We need to sort some things out in the project side.

CC: @rithviknishad

- [ ] Add badges relevant to the project in README.
- [x] Add installation section.
- [ ] Add development setup section.
- [ ] Add contributing section.
- [ ] Add copyright notice (?).
- [x] Dockerize Bakecode.
- [x] Dockerize development Bakecode.
- [ ] Add code of conduct
- [ ] Add issue template.
- [ ] Add pull request template.
- [ ] Add a master build script that will build Bakecode, Dockerize it and ship the final product.
- [ ] Add wiki section (?)
- [ ] #8
- [ ] Setup labels for issues.
